version: "3.9"

services:
  backend:
    tty: true
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - "./invoices:/usr/src/app/invoices"
    ports:
      - 8000:8000

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "invoice_db"
      POSTGRES_USER: "backend_app"
      POSTGRES_PASSWORD: "root"
    ports:
      - 5432:5432