"""removed user from invoice

Revision ID: 116d37dbed22
Revises: 891f710f8303
Create Date: 2024-05-14 23:32:57.814152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116d37dbed22'
down_revision: Union[str, None] = '891f710f8303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice', 'user_fk',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice', 'user_fk',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
